### ISSUE TITLE
get

### ISSUE THREAD

**Issue by Tom951** [EnolaLabs/Angular-Parse-Repositories#1]
Hi,

Line 87: I believe it's options.get.queries below, not options.all.queries

Regards,
Tom

     get: function(id) {
                        var defer = $q.defer();

                        var query = new Parse.Query(objectClass);

                        if(options.hasOwnProperty('get') && options.get.hasOwnProperty('queries')) {
                            for(var i = 0; i < options.get.queries.length; i ++) {
	                            eval(options.get.queries[i]);
                            }
                        }

**Comment by EnolaLabs** [comment]
@Tom951 Yes, you're correct. Sorry it's taken this long to get to this. Didn't have notifications turned on for issues. That bug is now fixed.

**Comment by Tom951** [comment]
Excellent, thanks!
