### ISSUE TITLE
Can I wrap up Parse.User()?

### ISSUE THREAD

**Issue by mescalito** [EnolaLabs/Angular-Parse-Repositories#7]
Hi!
Can I wrap ParseUser object on your library? 

There is a method called signUp (https://parse.com/docs/js/api/classes/Parse.User.html#methods_signUp) that I can't call when using your library CreateRepository. 

Is there a way to do so? or should I always work directly with "new Parse.User()" and avoid "CreateRepository()"?

```javascript
    var Users = $repos.CreateRepository('Users', {
        'all': {
            'queries': ['query.ascending("name");', 'query.limit(100);']
        }
    });
    $repos.GettersAndSetters(Users, [
        {angular: 'un',  parse: 'username'},
        {angular: 'pw',  parse: 'password'},
        {angular: 'e',  parse: 'email'},
        {angular: 'bd', parse: 'birthday'}
    ]);
    var user = new Users.create(); // this is Not a ParseUser Object, it is a ParseObjectSubClass
    var user2 = new Parse.User(); // // this is a ParseUser Object, I can do user.signUp()
```

Thanks!

**Comment by vsafin-copart** [comment]
You can add your own methods as described in the documentation. 
add signup method and user ParseUser.signup there

**Comment by mescalito** [comment]
Thanks for your answer! 
signUp() is a method from the Parse User Object (watch documentation: https://parse.com/docs/js/api/classes/Parse.User.html). 
I don't want to add me own methods this time, I want to use the ones from Parse User Object. There are many not available, how can I access them? 

allowCustomUserClass
authenticated
become
current
currentAsync
disableUnsafeCurrentUser
enableRevocableSession
enableUnsafeCurrentUser
extend
getEmail
getSessionToken
getUsername
isCurrent
logIn
logIn
logOut
requestPasswordReset
setEmail
setPassword
setUsername
signUp
signUp

Thanks!

**Comment by mescalito** [comment]
As you can see in my code, I created a User (var Users = $repos.CreateRepository('Users')) using CreateRepository(). I supposed I can access all methods from the native Parse User Object (watch documentation: https://parse.com/docs/js/api/classes/Parse.User.html) and also the all the methods added by CreateRepository. am I right or wrong?

**Comment by vsafin-copart** [comment]
Yes you should be ... you need to use Parse user type though "_User"

$repos.CreateRepository('_User',

**Comment by mescalito** [comment]
great! thanks!
